version: "3.3"

services:
  sdmap-agent-psm:
    build: 
      context: .
      dockerfile: Dockerfile
    networks: 
      - mqtt
    depends_on:
      - mosquitto
    environment:
      FORMAT: 1
      PUBFREQ: 10
      PUBSERVER: mosquitto:1883
      SUBSERVER: mosquitto:1883
      SUBTOPIC: psm
      PUBTOPIC: decoded_psm
    command: -log=debug
  
  jdecoder-test-pub-psm:
    build: 
      context: .
      dockerfile: pub.Dockerfile
    networks: 
      - mqtt
    depends_on:
      - mosquitto
    environment:
      PUBFREQ: 10
      PUBSERVER: mosquitto:1883
      PUBFILE: /app/psm.uper
      PUBTOPIC: psm
      SUBTOPIC: decoded_psm
    command: -log=debug
    volumes:
      - type: bind
        source: ./pkg/decoder/samples/psm1.uper
        target: /app/psm.uper

  sdmap-agent-bsm:
    build: 
      context: .
      dockerfile: Dockerfile
    networks: 
      - mqtt
    depends_on:
      - mosquitto
    environment:
      FORMAT: 0
      PUBFREQ: 10
      PUBSERVER: mosquitto:1883
      SUBSERVER: mosquitto:1883
      SUBTOPIC: bsm
      PUBTOPIC: decoded_bsm
      REVBEARING: 0
      EXPIRY: 1
    command: -log=debug
  
  jdecoder-test-pub-bsm:
    build: 
      context: .
      dockerfile: pub.Dockerfile
    networks: 
      - mqtt
    depends_on:
      - mosquitto
    environment:
      PUBFREQ: 10
      PUBSERVER: mosquitto:1883
      PUBFILE: /app/bsm.log
      PUBTOPIC: bsm
      SUBTOPIC: decoded_bsm
    command: -log=debug
    volumes:
      - type: bind
        source: ./pkg/decoder/samples/bsm.log
        target: /app/bsm.log

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    networks:
      - mqtt
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883"
      - "9001"

networks:
  mqtt: